server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    driver-class-name: org.postgresql.Driver
    password: sql101@postgresql
    url: jdbc:postgresql://localhost:5432/eazybank_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

info:
  app:
    name: "accounts"
    description: "Eazybank Cards microservice"
    version: "1.0"

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace.id},%X{span.id}]"

service:
  url: "http://localhost:9000/"