version: '3'
services:
  postgresql:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql101@postgresql
      - POSTGRES_DB=eazybank_db
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  accounts-service:
    image: accounts-service:1.0
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/eazybank_db
    depends_on:
      - postgresql
    links:
      - postgresql
volumes:
  postgresql-data:
    driver: local
