spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

#      routes:/
#        - id: after_route
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/api/**
#            - After=2023-12-05T19:03:47.789+03:00[Africa/Nairobi]
#          filters:
#            - RewritePath=/eazybank/accounts/(?<segment>.*), /$\{segment}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Api Gateway for Eazybank microservices"
    version: "1.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace.id},%X{span.id}]"

resilience4j.circuitBreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000