services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qa@sql101@postgresql
      - POSTGRES_DB=eazybank_db
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - eazybank
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 100m
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 5s
    extends:
      file: common-config.yaml
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 200m
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yaml
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 200m
  config-server:
    image: davidnkamura/configserver:1.0
    container_name: config-server
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-base-config
  eureka-server:
      image: davidnkamura/eurekaserver:1.1
      container_name: eureka-server
      ports:
        - 8070:8070
      healthcheck:
        test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
        interval: 5s
        timeout: 5s
        retries: 4
        start_period: 5s
      depends_on:
        config-server:
          condition: service_healthy
      networks:
        - eazybank
      environment:
        SPRING_APPLICATION_NAME: eurekaserver
        SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      deploy:
        resources:
          limits:
            memory: 400m
  accounts-service:
    image: davidnkamura/accounts-service:5.0
    container_name: accounts-service
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    environment:
      SPRING_APPLICATION_NAME: accounts
    links:
      - postgresql
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
  loans-service:
    image: davidnkamura/loans-service:4.0
    container_name: loans-service
    ports:
      - 8090:8090
    healthcheck:
      test: "curl --fail --silent http://localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    environment:
      SPRING_APPLICATION_NAME: loans
    links:
      - postgresql
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
  cards-service:
    image: davidnkamura/cards-service:4.0
    container_name: cards-service
    ports:
      - 9000:9000
    healthcheck:
      test: "curl --fail --silent http://localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    environment:
      SPRING_APPLICATION_NAME: cards
    links:
      - postgresql
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
  gateway-server:
    image: davidnkamura/gatewayserver:2.0
    container_name: gateway-server
    ports:
      - 9100:9100
    depends_on:
      accounts-service:
        condition: service_healthy
      cards-service:
        condition: service_healthy
      loans-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 400m
volumes:
  postgresql-data:
    driver: local
networks:
  eazybank:
    driver: "bridge"