build:
  version: "1.0"
accounts:
  message: "Welcome to the accounts microservice PRODUCTION API"
  contactDetails:
    name: "David Ngumbu Kamura - Lead Software Engineer"
    email: "davidngumbu115@eazybank.com"
  onCallSupport:
    - 0092828112
    - 0191281912