build:
  version: "2.0"
loans:
  message: "Welcome to the loans microservice QA API"
  contactDetails:
    name: "David Ngumbu Kamura"
    email: "davidngumbu115@gmail.com"
  onCallSupport:
    - 0892829210
    - 0293839393