spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:hachikko/eazybank-config.git"
          default-label: main
          timeout: 5
          refreshRate: 180
          cloneOnStart: true
          ignoreLocalSshSettings: true
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKQIBAAKCAgEAogb3OLtEb9fz8uPHfqIvH6s1LNqr3FT7mWftNd6gXZK4rgM1
            ovkvNj1btgqjHX4cTChsJQ5+gVSc/MHXQIgMdD15IJEUqx9kq7XLW770lO8OnxiW
            BxOvG3WiiKgAQOzpKwKDOgTkGdIHlyvtSElxYHqmoLZHTBPHENPnYc4g+OgyruXT
            G5rSiMVTUfUA5DzxTz+eLlfBQPt27xbtLsSZXGIfoLTTgeYt1wijJJQprlOjQzhA
            MSEXwbKkSrt3JY/i1hYHHfrW4R0q18JO72Vo6GpyM2Io9aEYJBQmzCwtdWl5R3tQ
            +DSj/JyAZxQNax2Di39Ofgowp5qWlaEzceDmfV8Ks0mOF9rjeE8PXPUN8AzxUze9
            0LUnWBgZ8MH+QWGxesVanJkZ4fAZlbBPE+OjnZ0DrYJXzKFXUuOeZrC87Zcn8RMq
            LkheRi9o25lF6dhO0jBxO099cVfNy3M1BZpugcM765ZmHIzKvbHmMiXRnK3od3wz
            wh3Oxyigmgm9JFP+I/gax+TlKdkwAYr0sSW2pKzcLuGDseBPw+zDC1GrG4CZK5xp
            HLTOKzrjfztjcHTGxAv1cqq9pkBUBfW2i8NLFe3l3E45/ECBwbCptafRNY/0cUr7
            qGJ9T2gBKYEjPK9EaixxqTE8Pp/Ll9RNYIqgqbFYOtYNELWI/p4zYiqmnVkCAwEA
            AQKCAgA70Jp/xRJ0v6J9bn19UF5ZMJlG38tGYdEoRueZVYCaSsoG44Rvj9JQEcLD
            p5WkE6RasSmLXJhzIkt6PA0883y1hOQsk6Kvsb02bryOOCaOvNoG/cqU/j1Mw9am
            4G6HiW5ixGCxkJCsv46xzjOg1gwW8/CDsAcOHNcGbVQkFTay7PWY/5s5u6QxfbdO
            sEYN/DmRagj5Tsg3Nx4nEa2p8EY1hrvqVhcnA1S056linZftlU7WR/Parz7X8R0Z
            wa8wnLe/FQ63kJy3Kk9gq4j8c9GQy4sxUPGSDFCfMRlJkp2NlMyDCRFRMA3B+fyl
            ERALFTA01WCiwxxHI5in0ITva3lrBLisJYMgjW5TDihRGCJq6e7qqDoLk3B1xfSH
            WnahwBxpyyEiHkbrNqA4itxoWiBiW2hp5DZs10Qkmpwyw5BKd6zHqAJOBCAxXYmO
            ieTxFPN6aeFoEm2xcjM32FunESZnRkNWRufFxXvwqJUFbEfhJqibGf6Yt+U+TMUS
            O8K4baTzQsNrTyvpRijpcu1DqbpuXspVGMGwYqziQxs058h73N43uQw8Jwg77gxg
            jrrdjKyO0oKVjRa5xfcRtIGRDZWdsoXW6LwaA+udZ7PGcsTJceYoMa4+QV+2WvZJ
            eMHd1Nd4j/UnEU6/P4YXpHzwig13eaZYlveDPVDptWOv3SJTAQKCAQEA0P6mgNRb
            zAzmxN06JdBBiXymPkfg7/oudc8ZupfAmaapuhOdlcDuqBrfZY3FSlCfHAHJPne+
            hTOf+nI+Y3WG1DP2jhE155dhKCCCVQMaSI5nCO3tTkp8+fD5xg39QAPyGoudLU9G
            ziJqFWcVRVznKn5379f3gyI7B2hIJ1OLs+SbPN0WrkCC+HSpxx/zRB47p44D8jwj
            rBU8SPVKMO+gvlhFvllkJs+bmsBh84tAYN5YIX8ZvTWWJ2xGXrBaTehkAz4kqUZ8
            YJ5DQa6RcxgSHZY5GGPcWcZmlpFuPDJAZB/jlLvBid5oneaAu8zAvMsLvw46pqKh
            VO0jPEi4CXA06QKCAQEAxngNkKyibK79a4Rm0f9IwvctWpaMvHp0oO9Mnf3EygI0
            XQndxfywLjRC7M5ERB36QKUPaIvMBf5JDJby6XdrFDlgc0IWl9wwdCGvNmJPowDd
            Sg04QGnJjncc2Wh48vsNe5XecDhpjMf2cxBvHunDeYiqNzRsC8P+PJF8r9iBcudZ
            SeN/dGcmS46WuXQ24GjF3is64SftTaxk5DowlD4TXeaytG+H7ngV9ez+/Ff2b8Wt
            rUnXrBLbasXvQHprym37aWag00ktd+wdMzo5fUv1xXSQ3ogjOgXeZi3kH2KkUIEN
            stf3HlfBquddB+ex3bosrJUaZDGBobPNQ5j3BlWe8QKCAQAzq7HoyhgEA/COHZAB
            x1Jctpe3cDf5vOX9tH1M97XjhyQRYEYmvzOCFlrDFeEANZyQ5RQnQJ22+wODfPlV
            x7nU/x/nEfQ81N1teVQfxouaArMQrxprr9jkRqLKR60kRZV24Ku0hxQfZLzLm9fT
            dVul0uy+PKvyHOVxOGQWbP5uNIf47URtQn/fA6DyHUEcx0jCbUcmfZ3oLrvf4d08
            6hHY3aQoopszSULUaNoOx4/cIzyw02a+s9/y0T84q+s3tcv8TUHtJAMeNCK2u300
            cnAQJpLpJ89T1syIT15svZPT7Vpr7Fu2RWmiGFodlErWonC+BLuVdUHj6Fk8z1HI
            65f5AoIBAQCXg69Xc3PMZQsyubGFP87ciLcnISfv+8xt0EI9my5Qyb4QCSg1reMS
            YvN0tUOIfRo/n8NTnOX07Vv3MIXhljk5B1SKqTl2VbLn9Y89hXAmkNJfZhg7lIc7
            K9PqZcdwOBji8FcQdQCfaUjMLw+mGfARKDRKUMrrcIT22FrIJBEvF08jCXqT8utZ
            Y1HN4trCFzp3kakxmrmfQq0DTyknAvzmAukKttqfQy4AwR0oqD6Kte8RC/6Kbxrz
            OIieQNdpgu0cWi0NICCGHMtuAFVDQmoug/7U5DmAYlqWxxIQo82tZ9h9YEJX98by
            Ig7zqf4vt6HDX1D2jJTaTdm2cWCkhVkBAoIBAQCYWpBMhucjSMw07RyOFLvT7W9g
            HTN9ADT2D3sfmMm2XY25O4BAogEOLTTi+MNZ4ciVQOXgjmU7FxMoUQqjiEBu7Jja
            ddpUVfkpUhQ8olEjUiwjB1xCZMPYHVkVp5hiJdx8xOaNU89HKvTFAN1Y+YBSrshT
            drAsEG8ULP+7wmJrRvSHK6shn1ZsK9pWmZEtvhQol0zzCigz5B5DRTzVdB2zB2Fy
            z5X7/sV80S0VQ+Q3+CVWuohr4bC1Gk9IuprSQzsv6gEn0qPqF5VwKxMfYiIHNEPa
            w0Sz5qb3alUxJ/G26BuP2D+CqyE+PmC6K0nJCOWI8Zcp5W6i/jCAtpSPfcGh
            -----END RSA PRIVATE KEY-----
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  #key: "AKEEI3+29294:2022kQKDS_KDSWEEEESKAKKAaaaK9YYK+9QWE"
  keyStore:
    location: classpath:/configkey.jks
    password: eazybankconfigkey101
    alias: eazybankconfigkey

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace.id},%X{span.id}]"

