spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:hachikko/eazybank-config.git"
          default-label: main
          timeout: 5
          refreshRate: 180
          cloneOnStart: true
          ignoreLocalSshSettings: true
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  #key: "AKEEI3+29294:2022kQKDS_KDSWEEEESKAKKAaaaK9YYK+9QWE"
  keyStore:
    location: classpath:/configkey.jks
    password: eazybankconfigkey101
    alias: eazybankconfigkey

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace.id},%X{span.id}]"

